name: CI

on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bleep-build/bleep-setup-action@0.0.1
      - uses: coursier/cache-action@v6
        with:
          extraFiles: bleep.yaml
      - run: bleep fmt --check

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: bleep-build/bleep-setup-action@0.0.1
      - uses: coursier/cache-action@v6
        with:
          extraFiles: bleep.yaml
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.bleep/builds/normal
          key: build-${{ hashFiles('bleep.yaml') }}
          restore-keys: |
            build-
      - name: Compile
        run: bleep compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: bleep-build/bleep-setup-action@0.0.1
      - uses: coursier/cache-action@v6
        with:
          extraFiles: bleep.yaml
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.bleep/builds/normal
          key: build-${{ hashFiles('bleep.yaml') }}
          restore-keys: |
            build-
      - name: Test
        run: bleep test
